apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azure-cosmos-db-secrets
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: ../localsecrets/azure-cosmos-db-secrets.json
    - name: nestedSeparator
      value: ':'
    - name: multiValued
      value: 'false'
