name: Deploy Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
 # Allow manual trigger 
  workflow_dispatch: 

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        - name: 'Login ACR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: Build and push DataGenerator
          uses: docker/build-push-action@v4
          with:
            push: true
            file: ./DataGenerator/Dockerfile
            context: .
            tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/wasm.api:latest
            
        - name: Build and push PatientGegevensService
          uses: docker/build-push-action@v4
          with:
            push: true
            file: ./PatientGegevensService/Dockerfile
            context: .
            tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/patientgegevensservice:latest
            
        - name: build and push PatientData
          uses: docker/build-push-action@v4
          with:
            push: true
            file: ./PatientData/Dockerfile
            context: .
            tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/patientdata:latest
        - name: build and push DokterService
          uses: docker/build-push-action@v4
          with:
            push: true
            file: ./Dokterservice/Dockerfile
            context: .
            tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/dokterservice:latest